[project]
name = "scratching-post-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shane B.", email = "dotfortun@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.140.13",
    "scalar-fastapi>=1.8.2",
]
